/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufms.apsoo.screens.Telas;

import br.ufms.apsoo.model.Venda;
import javax.swing.JLabel;

/**
 *
 * @author alexlinux
 */
public class ComprovanteDePagamento extends javax.swing.JFrame {
  private Venda venda;

  /**
   * Creates new form ComprovanteDePagamento
   */
  public ComprovanteDePagamento() {
    initComponents();

/**
    nomeCliente.setText(this.venda.getCliente().getNome());
    cpfCliente.setText(this.venda.getCliente().getCpf());
    codigoCarro.setText(this.venda.getCarro().getCodigo().toString());
    marcaCarro.setText(this.venda.getCarro().getMarca());
    modeloCarro.setText(this.venda.getCarro().getModelo());
    valorCarro.setText("" + this.venda.getCarro().getValor());
    formaPagamento.setText(this.venda.getFormaPagamento());
    parcelas.setText("" + this.venda.getNumParcelas());
    valorTotal.setText("" + this.venda.getValorTotal());
*/

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    nomeCliente = new javax.swing.JLabel();
    cpfCliente = new javax.swing.JLabel();
    codigoCarro = new javax.swing.JLabel();
    marcaCarro = new javax.swing.JLabel();
    modeloCarro = new javax.swing.JLabel();
    valorCarro = new javax.swing.JLabel();
    formaPagamento = new javax.swing.JLabel();
    parcelas = new javax.swing.JLabel();
    valorTotal = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setText("Comprovante De Pagamento");

    nomeCliente.setText("jLabel2");

    cpfCliente.setText("jLabel3");

    codigoCarro.setText("jLabel4");

    marcaCarro.setText("jLabel5");

    modeloCarro.setText("jLabel6");

    valorCarro.setText("jLabel7");

    formaPagamento.setText("jLabel8");

    parcelas.setText("jLabel9");

    valorTotal.setText("jLabel10");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
            layout.createSequentialGroup().addContainerGap(107, Short.MAX_VALUE).addComponent(jLabel1).addGap(92, 92,
                92))
        .addGroup(layout.createSequentialGroup().addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(nomeCliente)
                .addComponent(cpfCliente).addComponent(codigoCarro).addComponent(marcaCarro).addComponent(modeloCarro)
                .addComponent(valorCarro).addComponent(formaPagamento).addComponent(parcelas).addComponent(valorTotal))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel1).addGap(22, 22, 22)
            .addComponent(nomeCliente).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(cpfCliente).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(codigoCarro).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(marcaCarro).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(modeloCarro).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(valorCarro).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(formaPagamento).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(parcelas).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(valorTotal).addContainerGap(14, Short.MAX_VALUE)));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  public Venda getVenda() {
    return this.venda;
  }

  public void setVenda(Venda venda) {
    this.venda = venda;
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel. For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ComprovanteDePagamento.class.getName()).log(java.util.logging.Level.SEVERE,
          null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ComprovanteDePagamento.class.getName()).log(java.util.logging.Level.SEVERE,
          null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ComprovanteDePagamento.class.getName()).log(java.util.logging.Level.SEVERE,
          null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ComprovanteDePagamento.class.getName()).log(java.util.logging.Level.SEVERE,
          null, ex);
    }
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ComprovanteDePagamento().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel codigoCarro;
  private javax.swing.JLabel cpfCliente;
  private javax.swing.JLabel formaPagamento;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel marcaCarro;
  private javax.swing.JLabel modeloCarro;
  private javax.swing.JLabel nomeCliente;
  private javax.swing.JLabel parcelas;
  private javax.swing.JLabel valorCarro;
  private javax.swing.JLabel valorTotal;
  // End of variables declaration//GEN-END:variables
}
