/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufms.apsoo.screens.Telas;

import br.ufms.apsoo.controllers.CarroController;
import br.ufms.apsoo.controllers.ClienteController;
import br.ufms.apsoo.controllers.VendaController;
import br.ufms.apsoo.controllers.FuncionarioController;
import br.ufms.apsoo.model.Carro;
import br.ufms.apsoo.model.Cliente;
import br.ufms.apsoo.model.Venda;
import br.ufms.apsoo.model.Funcionario;
import java.awt.event.KeyEvent;
import static java.awt.event.KeyEvent.VK_ENTER;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.xml.bind.DatatypeConverter;

/**
 *
 * @author alexlinux
 */
public class TelaRealizarVenda extends javax.swing.JFrame {

  private VendaController vendaController = new VendaController();
  private ClienteController clienteController = new ClienteController();
  private CarroController carroController = new CarroController();
  private FuncionarioController funcionarioController = new FuncionarioController();

  private Funcionario funcionario;
  private Cliente cliente;
  private Carro carro;
  private Venda venda;

  private double valorCarro = 0;
  private double valorTotal = 0;
  private double valorEntrada = 0;
  private int numeroParcelas = 1;
  private String formaPagamento;

  private String marcaSelecionada;
  private String modeloDeCarroSelecionado;

  public TelaRealizarVenda() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jComboBox2 = new javax.swing.JComboBox<>();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    caixaTextoCPFCliente = new javax.swing.JTextField();
    caixaTextoNomeCliente = new javax.swing.JTextField();
    marcaBox = new javax.swing.JComboBox<>();
    modeloBox = new javax.swing.JComboBox<>();
    jLabel7 = new javax.swing.JLabel();
    campoTextoValorEntrada = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    vezesBox = new javax.swing.JComboBox<>();
    botaoConfirmar = new javax.swing.JButton();
    botaoCancelar = new javax.swing.JButton();
    jLabel9 = new javax.swing.JLabel();
    caixaTextoValorDoCarro = new javax.swing.JTextField();
    jLabel10 = new javax.swing.JLabel();
    caixaTextoValorTotal = new javax.swing.JTextField();
    formaPagamentoBox = new javax.swing.JComboBox<>();
    jLabel11 = new javax.swing.JLabel();
    caixaTextoCodigoGerente = new javax.swing.JTextField();
    jLabel12 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    caixaCpfFuncionario = new javax.swing.JTextField();
    jLabel13 = new javax.swing.JLabel();
    caixaTextoNomeFuncionario = new javax.swing.JTextField();
    jLabel14 = new javax.swing.JLabel();
    caixaCodigoDoCarro = new javax.swing.JTextField();

    jComboBox2
        .setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
    jLabel1.setText("Realizar Venda");

    jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
    jLabel2.setText("CPF Do Cliente:");

    jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
    jLabel3.setText("Nome:");

    jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
    jLabel4.setText("Marca:");

    jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
    jLabel5.setText("Modelo:");

    caixaTextoCPFCliente.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        caixaTextoCPFClienteActionPerformed(evt);
      }
    });
    caixaTextoCPFCliente.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        caixaTextoCPFClienteKeyPressed(evt);
      }
    });

    caixaTextoNomeCliente.setEditable(false);
    caixaTextoNomeCliente.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
    caixaTextoNomeCliente.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        caixaTextoNomeClienteActionPerformed(evt);
      }
    });

    marcaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
    marcaBox.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        marcaBoxMouseClicked(evt);
      }
    });
    marcaBox.addComponentListener(new java.awt.event.ComponentAdapter() {
      public void componentShown(java.awt.event.ComponentEvent evt) {
        marcaBoxComponentShown(evt);
      }
    });
    marcaBox.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        marcaBoxActionPerformed(evt);
      }
    });

    modeloBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
    modeloBox.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        modeloBoxMouseClicked(evt);
      }
    });
    modeloBox.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        modeloBoxActionPerformed(evt);
      }
    });

    jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
    jLabel7.setText("Valor de Entrada:");

    campoTextoValorEntrada.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        campoTextoValorEntradaActionPerformed(evt);
      }
    });

    jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
    jLabel8.setText("Parcelas:");

    vezesBox.setModel(
        new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "1", "12", "24", "36", "68", "72" }));
    vezesBox.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        vezesBoxActionPerformed(evt);
      }
    });

    botaoConfirmar.setText("Confirmar");
    botaoConfirmar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botaoConfirmarActionPerformed(evt);
      }
    });

    botaoCancelar.setText("Cancelar");
    botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botaoCancelarActionPerformed(evt);
      }
    });

    jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
    jLabel9.setText("Valor do Carro:");

    caixaTextoValorDoCarro.setEditable(false);
    caixaTextoValorDoCarro.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
    caixaTextoValorDoCarro.setDisabledTextColor(new java.awt.Color(0, 0, 0));
    caixaTextoValorDoCarro.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        caixaTextoValorDoCarroActionPerformed(evt);
      }
    });

    jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
    jLabel10.setText("Total:");

    caixaTextoValorTotal.setEditable(false);
    caixaTextoValorTotal.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
    caixaTextoValorTotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
    caixaTextoValorTotal.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        caixaTextoValorTotalActionPerformed(evt);
      }
    });

    formaPagamentoBox.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[] { "Selecione", "Parcelado", "Dinheiro", "Cartão De Crédito", "Cartão De Débito", "Cheque" }));
    formaPagamentoBox.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        formaPagamentoBoxActionPerformed(evt);
      }
    });

    jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
    jLabel11.setText("Código do Gerente:");

    jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
    jLabel12.setText("Forma De Pagamento:");

    jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
    jLabel6.setText("CPF Do Funcionário:");

    caixaCpfFuncionario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        caixaCpfFuncionarioActionPerformed(evt);
      }
    });
    caixaCpfFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        caixaCpfFuncionarioKeyPressed(evt);
      }
    });

    jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
    jLabel13.setText("Nome:");

    caixaTextoNomeFuncionario.setEditable(false);
    caixaTextoNomeFuncionario.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

    jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
    jLabel14.setText("Código Do Carro:");

    caixaCodigoDoCarro.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        caixaCodigoDoCarroKeyPressed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
        .createSequentialGroup().addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                    layout.createSequentialGroup().addGap(0, 0,
                        Short.MAX_VALUE).addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130,
                            javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup().addGroup(layout
                    .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup().addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9).addComponent(jLabel14)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13).addComponent(jLabel2))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                        layout.createSequentialGroup().addComponent(jLabel6).addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                        layout.createSequentialGroup().addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                        .createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(caixaTextoNomeCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caixaCodigoDoCarro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caixaTextoNomeFuncionario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caixaTextoCPFCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(marcaBox, javax.swing.GroupLayout.Alignment.LEADING, 0,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modeloBox, javax.swing.GroupLayout.Alignment.LEADING, 0,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(caixaCpfFuncionario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caixaTextoValorDoCarro)
                            .addComponent(formaPagamentoBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoTextoValorEntrada)
                            .addComponent(vezesBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(caixaTextoCodigoGerente, javax.swing.GroupLayout.DEFAULT_SIZE, 309,
                                Short.MAX_VALUE))
                        .addGap(76, 76, 76))
                        .addGroup(layout.createSequentialGroup().addGap(25, 25, 25).addComponent(jLabel1,
                            javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)))))
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7).addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup().addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(botaoConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 130,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caixaTextoValorTotal)))
                .addGap(130, 130, 130)))));
    layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
        .createSequentialGroup().addContainerGap()
        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(caixaCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel6))
        .addGap(14, 14, 14)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(caixaTextoNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel13))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(caixaTextoCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(caixaTextoNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(marcaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(modeloBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
        .addGap(5, 5, 5)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel14)
            .addComponent(caixaCodigoDoCarro, javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(caixaTextoValorDoCarro, javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel9))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(formaPagamentoBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel12))
        .addGap(7, 7, 7)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(campoTextoValorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel7))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(vezesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel8))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel11)
            .addComponent(caixaTextoCodigoGerente, javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(9, 9, 9)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(caixaTextoValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel10))
        .addGap(14, 14, 14).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(botaoConfirmar).addComponent(botaoCancelar))
        .addContainerGap()));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void caixaTextoCPFActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_caixaTextoCPFActionPerformed

  }// GEN-LAST:event_caixaTextoCPFActionPerformed

  private void caixaTextoNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_caixaTextoNomeClienteActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_caixaTextoNomeClienteActionPerformed

  private void marcaBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_marcaBoxActionPerformed
    marcaSelecionada = marcaBox.getSelectedItem().toString();
  }// GEN-LAST:event_marcaBoxActionPerformed

  private void modeloBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_modeloBoxActionPerformed
    modeloDeCarroSelecionado = modeloBox.getSelectedItem().toString();
  }// GEN-LAST:event_modeloBoxActionPerformed

  private void campoTextoValorEntradaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_campoTextoValorEntradaActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_campoTextoValorEntradaActionPerformed

  private void botaoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoConfirmarActionPerformed
    if (caixaTextoCPFCliente.getText().trim().equals("")) {
      JOptionPane.showMessageDialog(null, "CPF não preeenchido!", null, WIDTH);
    } else if (marcaBox.getSelectedItem().equals("Selecione")) {
      JOptionPane.showMessageDialog(null, "Escolha alguma marca!", null, WIDTH);
    } else if (modeloBox.getSelectedItem().equals("Selecione")) {
      JOptionPane.showMessageDialog(null, "Escolha algum modelo!", null, WIDTH);
    } else if (campoTextoValorEntrada.getText().trim().equals("")) {
      JOptionPane.showMessageDialog(null, "Digite um valor de entrada!", null, WIDTH);
    } else if (formaPagamentoBox.getSelectedItem().equals("Cheque")
        && caixaTextoCodigoGerente.getText().trim().equals("")) {
      JOptionPane.showMessageDialog(null, "Digite o código do gerente", null, WIDTH);
    }

    else {
      this.venda = vendaController.iniciarNovaVenda(this.valorEntrada, this.valorTotal, this.formaPagamento,
          this.numeroParcelas, this.funcionario.getCpf(), this.cliente.getCpf(), this.carro.getCodigo());
      if (this.venda == null) {
        JOptionPane.showMessageDialog(null, "Venda não realizada", null, WIDTH);
      } else {
        ConfirmacaoVenda telaConfirmacao = new ConfirmacaoVenda();
        telaConfirmacao.setVenda(venda);
        telaConfirmacao.setVisible(true);
      }
    }

  }// GEN-LAST:event_botaoConfirmarActionPerformed

  private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoCancelarActionPerformed
    this.setVisible(false);
    this.dispose();
  }// GEN-LAST:event_botaoCancelarActionPerformed

  private void formaPagamentoBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_formaPagamentoBoxActionPerformed
    switch (formaPagamentoBox.getSelectedItem().toString()) {
      case "Parcelado":
        caixaTextoCodigoGerente.setText("");
        campoTextoValorEntrada.setText("0");
        campoTextoValorEntrada.setEnabled(true);
        vezesBox.setEnabled(true);
        caixaTextoCodigoGerente.setEnabled(false);
        caixaTextoValorTotal.setEnabled(false);
        jLabel10.setText("Valor Parcelado: ");

        break;

      case "Dinheiro":
        caixaTextoCodigoGerente.setText("");
        campoTextoValorEntrada.setText("0");
        campoTextoValorEntrada.setEnabled(false);
        vezesBox.setEnabled(false);
        caixaTextoCodigoGerente.setEnabled(false);
        caixaTextoValorTotal.setText(String.format("R$ %.2f", this.valorTotal));
        caixaTextoValorTotal.setEnabled(false);
        jLabel10.setText("Total: ");

        break;
      case "Cartão De Crédito":
        campoTextoValorEntrada.setText("0");
        caixaTextoCodigoGerente.setText("");
        campoTextoValorEntrada.setEnabled(true);
        vezesBox.setEnabled(true);
        caixaTextoCodigoGerente.setEnabled(false);
        caixaTextoValorTotal.setEnabled(false);
        jLabel10.setText("Valor Parcelado: ");

        break;
      case "Cartão De Débito":
        caixaTextoCodigoGerente.setText("");
        campoTextoValorEntrada.setText("0");
        campoTextoValorEntrada.setEnabled(false);
        vezesBox.setEnabled(false);
        caixaTextoCodigoGerente.setEnabled(false);
        caixaTextoValorTotal.setText(String.format("R$ %.2f", this.valorTotal));
        caixaTextoValorTotal.setEnabled(false);
        jLabel10.setText("Total: ");

        break;
      case "Cheque":
        campoTextoValorEntrada.setText("0");
        campoTextoValorEntrada.setEnabled(false);
        vezesBox.setEnabled(false);
        caixaTextoCodigoGerente.setEnabled(true);
        caixaTextoValorTotal.setText(String.format("R$ %.2f", this.valorTotal));
        caixaTextoValorTotal.setEnabled(false);
        jLabel10.setText("Total: ");
      default:
        break;
    }
    this.formaPagamento = formaPagamentoBox.getSelectedItem().toString();

  }// GEN-LAST:event_formaPagamentoBoxActionPerformed

  private void caixaTextoValorDoCarroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_caixaTextoValorDoCarroActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_caixaTextoValorDoCarroActionPerformed

  private void caixaTextoValorTotalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_caixaTextoValorTotalActionPerformed

  }// GEN-LAST:event_caixaTextoValorTotalActionPerformed

  private void vezesBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_vezesBoxActionPerformed
    if (formaPagamentoBox.getSelectedItem().equals("Parcelado")
        || formaPagamentoBox.getSelectedItem().equals("Cartão De Crédito")) {
      String selecione = vezesBox.getSelectedItem().toString();
      if (selecione != "Selecione") {
        this.valorEntrada = Double.parseDouble(campoTextoValorEntrada.getText());
        this.numeroParcelas = Integer.parseInt(vezesBox.getSelectedItem().toString());
        double valorTemporario = (this.valorCarro - this.valorEntrada) / this.numeroParcelas;
        caixaTextoValorTotal.setText(String.format("R$ %.2f", valorTemporario));
      }
    } else {
      if (vezesBox.getSelectedItem().toString() != "Selecione") {
        this.numeroParcelas = 1;
        this.valorEntrada = 0;
      }
    }
  }// GEN-LAST:event_vezesBoxActionPerformed

  private void caixaTextoCPFClienteKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_caixaTextoCPFKeyPressed
    if (evt.getKeyCode() == VK_ENTER) {
      if (caixaTextoCPFCliente.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(null, "CPF não preeenchido!", null, WIDTH);
      } else {
        this.cliente = clienteController.buscar(caixaTextoCPFCliente.getText());
        if (this.cliente == null) {
          JOptionPane.showMessageDialog(null, "Cliente não cadastrado", null, WIDTH);
        } else {
          caixaTextoNomeCliente.setText(cliente.getNome());
        }
      }
    }
  }// GEN-LAST:event_caixaTextoCPFKeyPressed

  private void marcaCarro() {
    List<String> marcas = carroController.buscaMarcas();
    marcaBox.removeAllItems();
    marcas.forEach(c -> {
      marcaBox.addItem(c);
    });
  }

  private void modeloCarro() {
    List<Carro> modelos = carroController.buscaMarcaCarro(marcaSelecionada);
    modeloBox.removeAllItems();
    modelos.forEach(c -> {
      modeloBox.addItem(c.getCodigo() + " - " + c.getModelo());
    });
  }

  private void marcaBoxMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_marcaBoxMouseClicked
    marcaCarro();
  }// GEN-LAST:event_marcaBoxMouseClicked

  private void modeloBoxMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_modeloBoxMouseClicked
    modeloCarro();
  }// GEN-LAST:event_modeloBoxMouseClicked

  private void caixaCpfFuncionarioKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_caixaCpfFuncionarioKeyPressed
    if (evt.getKeyCode() == VK_ENTER) {
      if (caixaCpfFuncionario.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(null, "CPF não preeenchido!", null, WIDTH);
      } else {
        this.funcionario = funcionarioController.buscar(caixaCpfFuncionario.getText());
        if (this.funcionario == null) {
          JOptionPane.showMessageDialog(null, "Funcionário não cadastrado", null, WIDTH);
        } else {
          caixaTextoNomeFuncionario.setText(funcionario.getNome());
        }
      }
    }
  }// GEN-LAST:event_caixaCpfFuncionarioKeyPressed

  private void caixaCpfFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_caixaCpfFuncionarioActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_caixaCpfFuncionarioActionPerformed

  private void caixaCodigoDoCarroKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_caixaCodigoDoCarroKeyPressed
    if (evt.getKeyCode() == VK_ENTER) {
      if (caixaCodigoDoCarro.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(null, "Código não preeenchido!", null, WIDTH);
      } else {
        this.carro = carroController.buscarCarro(Integer.parseInt(caixaCodigoDoCarro.getText()));
        if (this.carro == null) {
          JOptionPane.showMessageDialog(null, "Carro não cadastrado", null, WIDTH);
        } else {
          this.valorCarro = this.carro.getValor();
          this.valorTotal = this.carro.getValor();
          caixaTextoValorDoCarro.setText(String.format("R$ %.2f", this.valorCarro));
          caixaTextoValorDoCarro.setEnabled(false);
        }
      }
    }
  }// GEN-LAST:event_caixaCodigoDoCarroKeyPressed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel. For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TelaRealizarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null,
          ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TelaRealizarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null,
          ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TelaRealizarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null,
          ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TelaRealizarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null,
          ex);
    }
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new TelaRealizarVenda().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton botaoCancelar;
  private javax.swing.JButton botaoConfirmar;
  private javax.swing.JTextField caixaCodigoDoCarro;
  private javax.swing.JTextField caixaCpfFuncionario;
  private javax.swing.JTextField caixaTextoCPFCliente;
  private javax.swing.JTextField caixaTextoCodigoGerente;
  private javax.swing.JTextField caixaTextoNomeCliente;
  private javax.swing.JTextField caixaTextoNomeFuncionario;
  private javax.swing.JTextField caixaTextoValorDoCarro;
  private javax.swing.JTextField caixaTextoValorTotal;
  private javax.swing.JTextField campoTextoValorEntrada;
  private javax.swing.JComboBox<String> formaPagamentoBox;
  private javax.swing.JComboBox<String> jComboBox2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JComboBox<String> marcaBox;
  private javax.swing.JComboBox<String> modeloBox;
  private javax.swing.JComboBox<String> vezesBox;
  // End of variables declaration//GEN-END:variables
}
